# Schema for the configuration files of the Entity Reference module.

entity_reference.default.handler_settings:
  type: mapping
  label: 'View handler settings'
  mapping:
    target_bundles:
      type: sequence
      label: 'types'
      sequence:
        - type: string
          label: 'Type'
    sort:
      type: mapping
      label: 'Sort settings'
      mapping:
        field:
          type: string
          label: 'Sort by'
        direction:
          type: string
          label: 'Sort direction'
    filter:
      type: mapping
      label: 'Filter settings'
      mapping:
        type:
          type: string
          label: 'Filter by'
        role:
          type: sequence
          label: 'Restrict to the selected roles'
          sequence:
            - type: string
              label: 'Role'
    auto_create:
      type: boolean
      label: 'Create referenced entities if they don''t already exist'
