# Schema for the configuration files of the Entity Reference module.

field.entity_reference.settings:
  type: mapping
  label: 'Settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.entity_reference.instance_settings:
  type: mapping
  label: 'Entity reference settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference.[%parent.handler].handler_settings
      label: 'Reference method settings'

field.entity_reference.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        target_id:
          type: integer
          label: 'Value'

entity_reference.default.handler_settings:
  type: mapping
  label: 'View handler settings'
  mapping:
    target_bundles:
      type: sequence
      label: 'types'
      sequence:
        - type: string
          label: 'Type'
    sort:
      type: mapping
      label: 'Sort settings'
      mapping:
        field:
          type: string
          label: 'Sort by'
        direction:
          type: string
          label: 'Sort direction'
    filter:
      type: mapping
      label: 'Filter settings'
      mapping:
        type:
          type: string
          label: 'Filter by'
        role:
          type: sequence
          label: 'Restrict to the selected roles'
          sequence:
            - type: string
              label: 'Role'
    auto_create:
      type: boolean
      label: 'Create referenced entities if they don''t already exist'
