# Schema for the configuration files of the Shortcut module.

shortcut.set.*:
  type: config_entity
  label: 'Shortcut settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    links:
      type: sequence
      label: 'Shortcuts'
      sequence:
        - type: string
          label: 'Shortcut'
