migrate.destination.entity:file:
  type: migrate_destination
  label: 'File'
  mapping:
    source_path_property:
      type: string
      label: 'Source path'
    source_base_path:
      type: string
      label: 'Source base path'
    urlencode:
      type: boolean
      label: 'Whether to urlencode incoming file paths'
