id: taxonomy_term.forums.forum_container
status: true
langcode: en
entity_type: taxonomy_term
bundle: forums
field_name: forum_container
label: Container
description: ''
required: true
default_value:
  -
    value: false
default_value_function: ''
settings: {  }
field_type: list_boolean
