id: bartik_search
theme: bartik
weight: -1
status: true
langcode: en
region: sidebar_first
plugin: search_form_block
settings:
  label: Search
  module: search
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
