id: bartik_powered
theme: bartik
weight: 10
status: true
langcode: en
region: footer
plugin: system_powered_by_block
settings:
  label: 'Powered by Drupal'
  module: system
  label_display: '0'
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
