id: bartik_login
theme: bartik
weight: 0
status: true
langcode: en
region: sidebar_first
plugin: user_login_block
settings:
  label: 'User login'
  module: user
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
