format: full_html
editor: ckeditor
settings:
  toolbar:
    buttons:
      -
        - Bold
        - Italic
        - Strike
        - Superscript
        - Subscript
        - -
        - RemoveFormat
        - '|'
        - Link
        - Unlink
        - '|'
        - BulletedList
        - NumberedList
        - '|'
        - Blockquote
        - Image
        - Table
        - HorizontalRule
        - '|'
        - Format
        - '|'
        - ShowBlocks
        - Source
  plugins:
    stylescombo:
      styles: ''
status: '1'
langcode: und
