id: user.user.default
targetEntityType: user
bundle: user
mode: default
content:
  user_picture:
    label: hidden
    type: image
    settings:
      image_style: thumbnail
      image_link: content
    weight: 0
status: true
