id: user.user.default
targetEntityType: user
bundle: user
mode: default
content:
  user_picture:
    type: image_image
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    weight: -1
status: true
