id: user.user.compact
targetEntityType: user
bundle: user
mode: compact
content:
  user_picture:
    label: hidden
    type: image
    settings:
      image_style: thumbnail
      image_link: content
    weight: 0
hidden:
  member_for: true
status: true
