id: comment.node__comment
targetEntityType: comment
bundle: node__comment
types:
  - 'schema:Comment'
fieldMappings:
  subject:
    properties:
      - 'schema:name'
  created:
    properties:
      - 'schema:dateCreated'
    datatype_callback:
      callable: 'date_iso8601'
  changed:
    properties:
      - 'schema:dateModified'
    datatype_callback:
      callable: 'date_iso8601'
  comment_body:
    properties:
      - 'schema:text'
  uid:
    properties:
      - 'schema:author'
    mapping_type: 'rel'
