name: thumbnail
label: 'Thumbnail (100x100)'
effects:
  1cfec298-8620-4749-b100-ccb6c4500779:
    name: image_scale
    data:
      width: '100'
      height: '100'
      upscale: '1'
    weight: '0'
    ieid: 1cfec298-8620-4749-b100-ccb6c4500779
langcode: en
