# Schema for the configuration files of the Contact module.

contact.category.*:
  type: config_entity
  label: 'Contact category'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    recipients:
      type: sequence
      label: 'Recipients'
      sequence:
        - type: email
          label: 'Email address'
    reply:
      type: text
      label: 'Auto-reply'
    weight:
      type: integer
      label: 'Weight'

contact.settings:
  type: mapping
  label: 'Contact settings'
  mapping:
    default_category:
      type: string
      label: 'Default category identifier'
    flood:
      type: mapping
      label: 'Flood control'
      mapping:
        limit:
          type: integer
          label: 'Limit'
        interval:
          type: integer
          label: 'Interval'
    user_default_enabled:
      type: boolean
      label: 'Personal contact form enabled by default'
