# Schema for the configuration files of the Serialization module.
serialization.settings:
  type: config_object
  label: 'Serialization settings'
  mapping:
    link_domain:
      type: string
      label: 'Domain of the relation'
