name: 'Configuration Environment'
type: module
description: 'Allows administrators to manage configuration environments.'
package: Core (Experimental)
version: VERSION
dependencies:
  - drupal:config
